all: direct_call direct_method_call

direct_call:
	@echo "Built target direct_call..."
	@gcc direct_call.c -o direct_call.out

direct_method_call:
	@echo "Build target direct_method_call..."
	@g++ direct_method_call.cpp -o direct_method_call.out

clean:
	rm -rf *.o
	rm -rf *.out
